Adding the optional product pathId param
idealo/terraform-provider-controltower pull request #48
Opened 2022-01-13 22:43 UTC by rayjanoka

Hi! I ran into this error when attempting to create an account:
```
Error: error provisioning account live: InvalidParametersException: More than one launch path ids exist. Please specify the launch path id
│ 
│   with controltower_aws_account.shared,
│   on env-aws.tf line 17, in resource "controltower_aws_account" "shared":
│   17: resource "controltower_aws_account" "shared" {
│ 
```

Somehow I have two of these "launch paths" assigned to my `AWS Control Tower Account Factory` product now, both are the same empty config. 

```
 ➜ aws servicecatalog list-launch-paths --product-id prod-123456
{
    "LaunchPathSummaries": [
        {
            "Id": "lpv2-123456",
            "ConstraintSummaries": [],
            "Tags": [],
            "Name": "AWS Control Tower Account Factory Portfolio"
        },
        {
            "Id": "lpv2-123123",
            "ConstraintSummaries": [],
            "Tags": [],
            "Name": "AWS Control Tower Account Factory Portfolio"
        }
    ]
}
```

Once you have more than one of these it is required to supply one of them in the request

aws docs
> The path identifier of the product. This value is optional if the product has a default path, and required if the product has more than one path. To list the paths for a product, use ListLaunchPaths. You must provide the name or ID, but not both.

There doesn't appear to be a way to remove these launch paths, I guess that is controlled by Control Tower. So after I applied this patch I was able to supply one of these launch path IDs and get my deployment completed.

thanks!

2022-01-21 13:42 UTC, mKeRix requested changes
Hey! 👋

Thank you for your contribution. That is an interesting edge case, certainly one we haven't seen before. I've left some comments on the code directly. Additionally, it would be awesome if you could do the following:

- implement the read part for the path id (you should be able to get it from the record details)
- regenerate the documentation by running `go generate`

2022-01-25 21:27 UTC, rayjanoka commented on internal/provider/resource_aws_account.go
> +		PathId:                 aws.String(pid),
I think I got it. thanks for the help!

2022-01-25 21:33 UTC, rayjanoka commented
Hey there, 

 Thanks for building the module and for the help with this. It looks like I've been flagged by SonarCloud but take a look and let me know what you think about the changes.

AWS is always going to return the `PathId` even if it wasn't explicitly set so everyone will see this when they run after updating.

```
  # controltower_aws_account.shared has been changed
  ~ resource "controltower_aws_account" "shared" {
        id                       = "pp-4p23z9999999"
        name                     = "development"
      + path_id                  = "lpv2-on7au6999999"
        tags                     = {
            "created_by" = "terraform"
            "owner"      = "devops"
        }
        # (4 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

─────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

```

2022-01-26 11:17 UTC, mKeRix approved these changes
LGTM! 🚀 

Thank you for the contribution.

2022-01-26 11:21 UTC, merged